test:
  sessions:
    default:
      database: mongoid_revisions_test
      hosts:
        - <%=ENV["MONGOID_SPEC_HOST"]%>:<%=ENV["MONGOID_SPEC_PORT"]%>
  # options:
  #   allow_dynamic_fields: true
  #   include_root_in_json: false
  #   include_type_for_serialization: false
  #   preload_models: false
  #   scope_overwrite_exception: false
  #   raise_not_found_error: true
  #   skip_version_check: true
  #   use_activesupport_time_zone: true
  #   use_utc: false
